#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: prometheus-config
#  namespace: monitoring
#  labels:
#    name: prometheus-config
#data:
#  prometheus.yml: |
#    global:
#      scrape_interval: 15s
#
#    scrape_configs:
#      - job_name: 'kubernetes-nodes'
#        kubernetes_sd_configs:
#          - role: node
#        relabel_configs:
#          - action: labelmap
#            regex: __meta_kubernetes_node_label_(.+)
#
#      - job_name: 'kubernetes-pods'
#        kubernetes_sd_configs:
#          - role: pod
#        relabel_configs:
#          - action: labelmap
#            regex: __meta_kubernetes_pod_label_(.+)

#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: prometheus-config
#  namespace: monitoring
#  labels:
#    name: prometheus-config
#data:
#  prometheus.yml: |
#    global:
#      scrape_interval: 15s
#
#    scrape_configs:
#      - job_name: 'kubernetes-nodes'
#        kubernetes_sd_configs:
#          - role: node
#        relabel_configs:
#          - action: labelmap
#            regex: __meta_kubernetes_node_label_(.+)
#
#      - job_name: 'kubernetes-pods'
#        kubernetes_sd_configs:
#          - role: pod
#        relabel_configs:
#          - action: labelmap
#            regex: __meta_kubernetes_pod_label_(.+)
#
#      - job_name: 'jenkins-ec2'
#        static_configs:
#          - targets: ['10.0.2.161:9100']
#            labels:
#              instance: jenkins-node

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-nodes'
        scheme: https
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics


      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)

      - job_name: 'jenkins-ec2'
        static_configs:
          - targets: ['10.0.2.161:9100']
            labels:
              instance: jenkins-node

      - job_name: 'python-app'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: python-app
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            replacement: $1
          - source_labels:
              [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+);(.+)
            replacement: $1:$2
      
