version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: python-redis-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis  # Pointing to the Redis container
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
