apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: prod  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: python-app
          image: 340752816389.dkr.ecr.us-east-1.amazonaws.com/python-app:latest
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: prod
              value: "prod"  # Change to 'prod' for production
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: metrics