- name: Install Jenkins and DevOps Tools
  hosts: jenkins
  become: true
  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install dependencies
      apt:
        name:
          - wget
          - gnupg
          - fontconfig
          - openjdk-17-jre
          - awscli
          - docker.io
        state: present

    - name: Download Jenkins key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        filename: jenkins
        state: present

    - name: Update APT cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Open firewall port 8080 for Jenkins
      ufw:
        rule: allow
        port: '8080'
        proto: tcp

    - name: Enable UFW firewall
      ufw:
        state: enabled

    - name: Download latest stable kubectl version
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -s https://cdn.dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/kubectl
      args:
        executable: /bin/bash

    - name: Add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

- name: Configure kubeconfig for Jenkins to access EKS
  hosts: jenkins
  become: true
  vars:
    cluster_name: devops-cluster
    region: us-east-1
  tasks:

    - name: Ensure .kube directory exists for Jenkins user
      file:
        path: /home/jenkins/.kube
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Debug AWS credentials
      debug:
        msg: "AWS Access Key ID: {{ aws_access_key_id }}"

    - name: Debug AWS credentials
      debug:
        var: aws_access_key_id

    - name: Print all variables for Jenkins group
      debug:
        var: hostvars[inventory_hostname]


    - name: Generate kubeconfig using AWS CLI for Jenkins
      shell: |
        aws eks --region {{ region }} update-kubeconfig --name {{ cluster_name }} --kubeconfig /home/jenkins/.kube/config
      environment:
        HOME: /home/jenkins
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      args:
        creates: /home/jenkins/.kube/config


    - name: Set permissions on kubeconfig file
      file:
        path: /home/jenkins/.kube/config
        owner: jenkins
        group: jenkins
        mode: '0600'
