---
- name: Install Docker, kubectl, AWS CLI, and Jenkins on Jenkins EC2
  hosts: jenkins
  become: true

  vars:
    eks_cluster_name: "devops-cluster"  # 🔁 Replace with your EKS cluster name

  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install required packages
      apt:
        name:
          - wget
          - curl
          - gnupg
          - apt-transport-https
          - ca-certificates
          - python3-pip
          - unzip
          - software-properties-common
          - fontconfig
          - openjdk-17-jre
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install kubectl
      shell: |
        K8S_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
        curl -LO "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/kubectl
      args:
        executable: /bin/bash


    - name: Check kubectl version
      command: kubectl version --client
      register: kubectl_version
      failed_when: kubectl_version.rc != 0
      become: true

    - debug:
        msg: "kubectl version installed successfully"


    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        ./aws/install
      args:
        executable: /bin/bash
      register: awscli_install
      changed_when: "'aws' in awscli_install.stdout"

    - name: Configure kubeconfig for EKS cluster
      become: false
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
      shell: |
        aws eks update-kubeconfig --name {{ eks_cluster_name }} --region {{ lookup('env', 'AWS_DEFAULT_REGION') }}
      args:
        executable: /bin/bash

    - name: Download Jenkins key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        filename: jenkins
        state: present

    - name: Update APT cache after Jenkins repo
      apt:
        update_cache: yes

    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Allow Jenkins port through UFW
      ufw:
        rule: allow
        port: '8080'
        proto: tcp

    - name: Enable UFW firewall
      ufw:
        state: enabled
